### ISSUE TITLE
[solidjs-pod] Showcase Clean Up

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1035]
We need a general proofing and cleanup of the work that has been done to make sure there are no errors or omissions. 

## Acceptance Criteria

- [ ] Review the current showcase is free of errors, and everything expected has been included and is operating as expected.

Timebox: max 2 hours each

## Who has completed this:
- [x] Daian
- [x] Chinedu
- [x] Mark
- [x] Mattia
- [x] Jerry

**Comment by SDaian** [comment]
We discover with @Megio the next things:
- Missing header on repo view
- Missing file navigation, the folder navigation seems to work but on nested folders sometimes break
- Missing chevron on the Profile dropdown
- Missing styles on the Home page

cc: @kenslachtajr maybe you can create some tickets for that

**Comment by kenslachtajr** [comment]
These tickets have been created. Thank you for your review.

**Comment by AllStackDev1** [comment]
Issues I discovered;

- File and Folders not sorted
- App crashes when trying to navigate to a repo file
- App crashes when trying to navigate the 2nd folder in a repo folder
- No pagination buttons in the profile page
