### ISSUE TITLE
[qwik-pod] Repo folder navigation return a 404

### ISSUE THREAD

**Issue by Megio** [thisdot/starter.dev-github-showcases#1068]
We are able to manage a blob in our url:

.../blob/master/%E2%80%A4github?forkCount=3672&watcherCount=677&stargazerCount=32803&issuesCount=548&prCount=163

but not tree :
.../tree/master/%E2%80%A4github?forkCount=3672&watcherCount=677&stargazerCount=32803&issuesCount=548&prCount=163

**Comment by AllStackDev1** [comment]
Does this exist? I believe you aren't on the main branch

**Comment by AllStackDev1** [comment]
This [PR](https://github.com/thisdot/starter.dev-github-showcases/pull/1033) closes this ticket.
