### ISSUE TITLE
[qwik-pod] Accessing a File is not showing anything

### ISSUE THREAD

**Issue by SDaian** [thisdot/starter.dev-github-showcases#1072]
Trying to access something like `blob/master/README.md/` is not populating the component with the content of the file.

![image](https://user-images.githubusercontent.com/14813235/207902273-69a06d64-28f7-49e0-9b68-ebbdf05239d7.png)

**Comment by AllStackDev1** [comment]
This has been fixed here https://github.com/thisdot/starter.dev-github-showcases/issues/1085
