### ISSUE TITLE
[qwik-graphql-tailwind] P1: Search On Profile Page Needs Fixed And Remove Double Profile Page

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1084]
- For Milestone 2: searching on the profile page doesn't find results but also shows a 2nd profile page on the same page

![Image](https://user-images.githubusercontent.com/1828602/208019238-45510c7d-e0c2-4290-adba-0681eb038252.png)

**Comment by AllStackDev1** [comment]
Currently, can't reproduce this issue locally and on production. I will suggest another check to see if the last build fixed it. @kenslachtajr @dustinsgoodman

**Comment by dustinsgoodman** [comment]
I didn't see this in our demo. Seems like maybe an issue with the deployment.
