### ISSUE TITLE
[svelte-kit-scss] P1: Fix Repo Links - Not Working

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1088]
- P1: most repos 500 when I click into them

**Comment by dustinsgoodman** [comment]
This was on the deployment that sounded broken fwiw.

**Comment by dustinsgoodman** [comment]
Resolved via https://github.com/thisdot/starter.dev-github-showcases/commit/d75e6ab53eb67c33fe3e4be1982038ce62655a94
