### ISSUE TITLE
[solidjs-tailwind] Clear "X" on filter dropdowns is not currently operational

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1134]
# Description
- when clicking the X in a filter dropdown nothing happens, and no currently selected filters are cleared. Expected behavior is that currently selected filters would be cleared when the X is clicked

![Image](https://user-images.githubusercontent.com/1828602/209015693-5e715594-1bfe-4fd3-8a17-96069e1e5861.png)

**Comment by AllStackDev1** [comment]
I second this and will close the issue
