### ISSUE TITLE
[svelte-kit-scss] Style README row width to match files row

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1187]
# Decription
- the README row is wider than the other file rows (see image)
- Also, rounded corners between the heading and the contents of the README.

![Image](https://user-images.githubusercontent.com/1828602/211255281-719e2b7b-2c98-4103-aca9-48c1d6296864.png)

**Comment by kodejuice** [comment]
Cant replicate, this is what i see:

![Image](https://user-images.githubusercontent.com/9017620/211596720-0b448517-7393-4304-aa1b-abd895bfc9b6.png)
