### ISSUE TITLE
[Angular - NgRx - SCSS] Get all repositories from GitHub API

### ISSUE THREAD

**Issue by lindakatcodes** [thisdot/starter.dev-github-showcases#120]
# Get all repositories from GitHub API

## Background

On a user’s profile page, we want to list out ALL of their repositories - not just the top ones. This ticket will be to get the data on all of a user’s repos for display on the profile page. 

## Acceptance

- [ ] Get all repositories from GitHub API
- [ ] For display on profile page; data needed:
    - [ ] Repo name
    - [ ] description
    - [ ] language
    - [ ] star count
    - [ ] fork count
    - [ ] last updated
    - [ ] visibility tag

## Notes

- This query should start sorted by most recently updated.

**Comment by SDaian** [comment]
This was addressed by @Reshurum on #118
