### ISSUE TITLE
[svelte-kit-scss] Add styling to README preview

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1226]
# Description
- currently the README preview does not have styling for links and table borders, etc, and should be added. This is optional and should only by taken on if/when all other showcase work has been completed

Current styling (present): 

![Image](https://user-images.githubusercontent.com/1828602/211868103-3d360e8c-4a17-4ae0-bb90-e0254ad484e7.png)

Repo view on Github (desired):

![Image](https://user-images.githubusercontent.com/1828602/211867794-938371b2-8ee4-40e7-9f23-28b04252a704.png)

**Comment by kodejuice** [comment]
may be helpful: https://www.azureblue.io/how-to-properly-style-a-markdown-table/
