### ISSUE TITLE
[solidjs-tailwind] Label filters not static once value is selected

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1328]
# Description

![Image](https://user-images.githubusercontent.com/1828602/214487463-d4403e4a-12e7-499d-9716-ed9f6411e4eb.png)

**Comment by Megio** [comment]
This is a common behavior for every kit. It is due to the response of API call and pagination. We can retrieve only the label on the current page, so when we filter, the only label displayed is the same one we have set as the filter parameter.
