### ISSUE TITLE
[VUE + TS + Quasar] Get Profile information from GitHub API

### ISSUE THREAD

**Issue by hdJerry** [thisdot/starter.dev-github-showcases#137]
## Background

For the profile page, we want to fairly closely resemble the GitHub user page. This section is focused on the user “card”, where you can see profile information about the user.

## Acceptance

- [x] Get user info from GitHub API
- [x] For display on profile page; data needed:
    - [x] Photo
    - [x] Name (display name)
    - [x] username (login name)
    - [x] description
    - [x] followers
    - [x] following
    - [x] stars
    - [x] company info
    - [x] location info
    - [x] blog link
    - [x] organizations (need name and avatar)

## Notes

**Comment by AllanJeremy** [comment]
## How to test
To test this, visit your local application at `localhost:8080/:username` for example: `localhost:8080/AllanJeremy` or visit the [production app](https://vue3-ts-quasar.starter.dev)

## Progress
Implemented this fully as far as specs listed here are concerned, however there's currently a few issues with the actual user profile page:

- [ ] Replace SVG with `<q-icon></q-icon>`
- [ ] Refactor to use majorly quasar classes for styling
- [ ] Refactor components that exist in quasar but are currently HTML to be quasar components
- [ ] Redirect to 404 if a user is not found (Prefer emitting `notFound` and have a global handler that redirects to 404 page
- [ ] Redirect to login page if user is not logged in
