### ISSUE TITLE
[solidstart-tanstack-tailwind] Showcase clean up

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1406]
We need a general proofing and cleanup of the work that has been done to make sure there are no errors or omissions. 

## Acceptance Criteria

- [ ] Review the current showcase is free of errors, and everything expected has been included and is operating as expected.
- [ ] Run the scripts in package.json and make sure that all run as expected without errors
- [ ] Review README and make sure it is complete without spelling errors or omissions

Timebox: max 2 hours each

## Who has completed this:
- [ ] Daian
- [x] Mark
- [ ] Mattia
- [x] Adam
- [ ] Chinedu

**Comment by Megio** [comment]
Missing Tab Header and pagination on Profile Page:



![Image](https://user-images.githubusercontent.com/32470461/219073113-b4b7b04d-e2b1-4f63-beeb-53856239a76a.png)



![Image](https://user-images.githubusercontent.com/32470461/219073164-249f03a2-df65-49e1-b216-586809743aa3.png)

**Comment by AllStackDev1** [comment]
The profile page -> http://localhost:3000/[login] should have the loading animation instead of text -> Loading...

**Comment by AllStackDev1** [comment]
Followers and Following counts not displaying correct values - always zero

![Image](https://user-images.githubusercontent.com/36667083/219080025-a7256e50-d77c-4fdc-8887-a0d0d26ae6b9.png)

**Comment by Megio** [comment]
Missing pagination also in the org page (and tab nav maybe)

**Comment by AllStackDev1** [comment]
Logging out doesn't redirect user to signin page,  in pages other than the home page.

**Comment by markshenouda** [comment]
After the review, I didn't any bugs but there are few minor things 

- - There are some imports with a double component names like this across the project
![Image](https://user-images.githubusercontent.com/49324987/224066030-9e75e928-c7d2-4b24-a9e5-38c22102fb9e.png)

- `<LoadingPulseDot />` should be centered

![Image](https://user-images.githubusercontent.com/49324987/224066595-89f4f0e5-69f3-4182-85df-34a7e3a7ff4c.png)

**Comment by mbicknese** [comment]
Superseded by #1527
