### ISSUE TITLE
[seven-guis-sveltekit] Create reusable links component

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1510]
# Description
As we will be using links in all of the 7 GUIs, let's create a links component that can be reused. 

# Acceptance Criteria
- [ ] Reusable links component has been created. It has the ability to be reused anywhere in the application.

# Notes
n/a

**Comment by dustinsgoodman** [comment]
Created in the wrong repo. Closing.
