### ISSUE TITLE
[seven-guis-sveltekit] Set up GUIs reusable page layout

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1511]
# Description
Each GUIs example has a similar page structure and we want to create a page structure template to be reused on each page. 

# Acceptance Criteria
- [ ] Page includes title, sub-title, text body, and box for the GUI itself
- [ ] Page template includes basic styling for each section for uniformity 

![Image](https://user-images.githubusercontent.com/1828602/221110785-3e4488f2-6cc9-49a6-86db-c2540aa8b8ac.png)

**Comment by dustinsgoodman** [comment]
Created in the wrong repo. Closing.
