### ISSUE TITLE
[solidstart-tanstack-tailwind] Showcase clean up

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1527]
We need a general proofing and cleanup of the work that has been done to make sure there are no errors or omissions. 

## Acceptance Criteria

- [ ] Review the current showcase to assure it is free of errors, and everything expected has been included and is operating as expected.
- [ ] Run the scripts in package.json and make sure that they all run as expected without errors.
- [ ] Review README and make sure it is complete without spelling errors or omissions.

Timebox: max 2 hours each

## Who has completed this:
- [x] Mattia
- [x] Chinedu
- [x] Mark
- [x] Jerry

**Comment by Megio** [comment]
When we go to `closed` tab in both the pull requests and issues page, the Pagination component disappears (everything works fine in the `open` tab).

**Comment by Megio** [comment]
On the profile page, we can navigate through pagination also when the second page has no results.

Steps to reproduce:

- go to profile page
- filter by something (search or language or type) 
- navigate pages with next button
- you can see that we can reach a page like this after clicking the next button

Expected behaviour:

Next button should be disabled when the next page has no results to show



![Image](https://user-images.githubusercontent.com/32470461/223089025-92134497-7ac0-4446-970a-fa8adee6f4ba.png)

**Comment by Megio** [comment]
Sort by most commented doesn't work on issues page

**Comment by Megio** [comment]
storybook doesn't work

**Comment by Megio** [comment]
loading dots component needs more margin-top when it is showed

**Comment by kenslachtajr** [comment]
Unexpected behavior: Clicking on organization under profile view goes to repos overview page.


![Image](https://user-images.githubusercontent.com/1828602/223633824-58373813-bdd5-4d2e-8290-1a8548531221.png)

**Comment by kenslachtajr** [comment]
`npm run format` changes files


![Image](https://user-images.githubusercontent.com/1828602/223635140-bd35f21f-cbd0-4be0-82ab-d6e6c3bf5d33.png)

**Comment by markshenouda** [comment]
After the review, I didn't any bugs but there are few minor things 

- - There are some imports with a double component names like this across the project
![Image](https://user-images.githubusercontent.com/49324987/224066030-9e75e928-c7d2-4b24-a9e5-38c22102fb9e.png)

- `<LoadingPulseDot />` should be centered

![Image](https://user-images.githubusercontent.com/49324987/224066595-89f4f0e5-69f3-4182-85df-34a7e3a7ff4c.png)

**Comment by mbicknese** [comment]
Starting a production server fails with the following error

> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'undici' imported from /Users/maarten/ThisDot/starter.dev-github-showcases/solidstart-tanstackquery-tailwind-modules/dist/server.js
