### ISSUE TITLE
[expo-zustand-styledcomponents] Showcase clean up

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1592]
We need a general proofing and cleanup of the work that has been done to make sure there are no errors or omissions. 

## Acceptance Criteria

- [ ] Review the current showcase to assure it is free of errors, and everything expected has been included and is operating as expected.
- [ ] Run the scripts in package.json and make sure that they all run as expected without errors.
- [ ] Review README and make sure it is complete without spelling errors or omissions.

Timebox: max 2 hours each

## Who has completed this:
- [x] Jerry
- [x] Chinedu
- [ ] Maarten

**Comment by AllStackDev1** [comment]
We do need tickets for the following;
[ ] Research and implementation for URL Integration/Linking for web
[ ] Passing data via the route path instead of the store, just like in other showcases
[ ]

**Comment by AllStackDev1** [comment]
![Image](https://user-images.githubusercontent.com/36667083/227515766-96ba4176-fcf2-4da8-bffb-4aa43a1052dd.png)

![Image](https://user-images.githubusercontent.com/36667083/227516083-2c9fd3d8-ea0c-487a-9ff8-0a88b47b5866.png)

Issues and Pull Tab appear somehow on mobile and some CSS are not allowed on mobile

**Comment by AllStackDev1** [comment]
![Image](https://user-images.githubusercontent.com/36667083/227522222-4fe1585b-aff4-4f6a-9576-092565f39526.png)


![Image](https://user-images.githubusercontent.com/36667083/227522134-f690da18-e878-471c-aa61-a4928e639c13.png)

The markdown package doesn't support tables and HTML and it is throwing some error warning, we need to replace this package. suggsestion -> https://www.npmjs.com/package/react-native-markdown-package

**Comment by Megio** [comment]
there is no "clear filter" button when we sort or filters the repo PRs or issues

**Comment by Megio** [comment]
on the issues and on the pr page, when I navigate through pages every time I am in a query loading status the total count number for open and closed issues or pr goes to zero, and then when the query is in the success status we see it again. That number should be fixed and not dependent on all the query statuses.



![Image](https://user-images.githubusercontent.com/32470461/227593896-c5815534-5e48-46b0-a1cc-e5673d39a396.png)

**Comment by hdJerry** [comment]
- The Links on the repo header are not functional.

**Comment by hdJerry** [comment]
- There is a need to separate the sign-in button from its loading state
- There is a need to handle failed login error, at the moment, the loading state remains and the button can still be clicked in its loading state

**Comment by hdJerry** [comment]
- source.uri should not be an empty string (A warning), I think we can try fix this if possible too

**Comment by hdJerry** [comment]
We need i little more spacing between the file/folder name and the icon


![Image](https://user-images.githubusercontent.com/28502531/227945407-f91bb20f-90f3-4ec6-a74d-56c3cf16cafb.jpg)

**Comment by hdJerry** [comment]
spacing is needed between these elements.

![Image](https://user-images.githubusercontent.com/28502531/228232619-8c319668-19f8-4dbc-9edd-5db476f9293e.jpg)

**Comment by hdJerry** [comment]
The first time you log in and click the profile dropdown on the header, the dropdown doesn't show until you refresh the page.
I believe this is due to how the toggle is handled.

**Comment by hdJerry** [comment]
Reduce the padding left on this page


![Image](https://user-images.githubusercontent.com/28502531/228257831-1ef9786a-098d-42e3-88a2-f35473451193.jpg)

**Comment by AllStackDev1** [comment]
Updating the usage of pagination in Issues and Pull Request screen to make use of web deep linking instead of state

**Comment by hdJerry** [comment]
Our top repo card title displays as this `reponame`


![Image](https://user-images.githubusercontent.com/28502531/228509331-52de6989-82d0-45a7-9d1d-43d616c43663.jpg)


But should be like this `owner/reponame`


![Image](https://user-images.githubusercontent.com/28502531/228509739-7e94f4b4-0dcd-4419-a018-9bfc20f5c2a7.jpg)

**Comment by AllStackDev1** [comment]
Home page - Top Repos doesn't scroll to the bottom.

![Image](https://user-images.githubusercontent.com/36667083/228893911-387f0591-70d1-4d70-9e43-f5eef1edd00c.png)

@kenslachtajr
