### ISSUE TITLE
[solidstart-tanstack-tailwind] Write blog post detailing challenges of SSR with SolidStart and Tanstack Query v4

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#1629]
# Description
- In working to implement server-side rendering in this showcase there were issues encountered that made this difficult, if not impossible. We have decided to leave the showcase "as-is" for now, but we need to write a blog post detailing these challenges and our journey in arriving at this decision.

**Comment by mbicknese** [comment]
https://docs.google.com/document/d/1Y2hKaB3-v4QiOaSnZKEY8ILLVpaBiIT7BHFMh0hyAk0/edit
