### ISSUE TITLE
[Bug]: solidjs-tailwind starter returns error

### ISSUE THREAD

**Issue by frankhinek** [thisdot/starter.dev-github-showcases#1817]
### What showcase are you using?

solidjs-tailwind

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

macOS

### Actual Behavior

When I follow the [Installation](https://github.com/thisdot/starter.dev/tree/main/starters/solidjs-tailwind#installation) steps from the solidjs-tailwind project and attempt to view the project in a browser, the following error is returned:

Chrome:
```
caught TypeError: _tmpl$ is not a function
    at App.jsx:5:3
    at App (App.jsx:10:43)
    at @solid-refresh:10:42
    at untrack (dev.js:427:12)
    at Object.fn (@solid-refresh:10:28)
    at runComputation (dev.js:708:22)
    at updateComputation (dev.js:691:3)
    at createMemo (dev.js:244:10)
    at hmrCompWrapper (@solid-refresh:7:20)
    at dev.js:527:12
```

Safari:
```
[Error] TypeError: _tmpl$ is not a function. (In '_tmpl$()', '_tmpl$' is an instance of HTMLDivElement)

	handleError (chunk-DXLZ6EHS.js:1079)
	runUpdates (chunk-DXLZ6EHS.js:893)
	createRoot (chunk-DXLZ6EHS.js:185)
	render (chunk-L73OVWMH.js:173)
	Module Code (index.jsx:8)
```

Firefox
```
Uncaught TypeError: _tmpl$ is not a function
    App App.jsx:5
    App App.jsx:10
    hmrCompWrapper @solid-refresh:10
    untrack dev.js:427
    hmrCompWrapper @solid-refresh:10
    runComputation dev.js:708
    updateComputation dev.js:691
    createMemo dev.js:244
    hmrCompWrapper @solid-refresh:7
    c dev.js:527
    untrack dev.js:427
    c dev.js:523
    runComputation dev.js:708
    updateComputation dev.js:691
    devComponent dev.js:533
    createComponent dev.js:1255
    get children index.jsx:9
    get children components.jsx:11
    res dev.js:994
    runComputation dev.js:708
    updateComputation dev.js:691
    createMemo dev.js:244
    children dev.js:589
    res dev.js:994
    untrack dev.js:427
    provider dev.js:990
    runComputation dev.js:708
    updateComputation dev.js:691
    createRenderEffect dev.js:211
    provider dev.js:990
    c dev.js:527
    untrack dev.js:427
    c dev.js:523
    runComputation dev.js:708
    updateComputation dev.js:691
    devComponent dev.js:533
    createComponent dev.js:1255
    Router components.jsx:11
    c dev.js:527
    untrack dev.js:427
    c dev.js:523
    runComputation dev.js:708
    updateComputation dev.js:691
    devComponent dev.js:533
    createComponent dev.js:1255
    <anonymous> index.jsx:9
    render dev.js:93
    updateFn dev.js:174
    runUpdates dev.js:810
    createRoot dev.js:182
    render dev.js:91
    <anonymous> index.jsx:8
```

### Expected Behavior

I should be able to `pnpm install`, `pnpm run dev`, and view the starter sample functions in a modern browser.

### Reproduction

This issue occurs whether I following the CLI or Manual steps from https://github.com/thisdot/starter.dev/tree/main/starters/solidjs-tailwind#installation

### CLI

```shell
pnpm create @this-dot/starter --kit solidjs-tailwind
```

- Follow the prompts to select the SolidJS and TailwindCSS starter kit and name your new project.
- `cd` into your project directory and run pnpm install.
- Run `pnpm run dev` to start the development server.
- Open your browser to http://localhost:3000 to see the included example code running.

OR

### Manual

```shell
git clone https://github.com/thisdot/starter.dev.git
```

- Copy and rename the `starters/solidjs-tailwind` directory to the name of your new project.
- `cd` into your project directory and run `pnpm install`.
- Run `pnpm run dev` to start the development server.
- Open your browser to http://localhost:3000 to see the included example code running.

**Comment by jesus4497** [comment]
Thank you for submitting this @frankhinek! 

The showcase and kit are fixed now 🤘
