### ISSUE TITLE
[Angular - NgRx - SCSS] Create user profile card

### ISSUE THREAD

**Issue by lindakatcodes** [thisdot/starter.dev-github-showcases#188]
# Create user profile card

## Background

As a user, when I visit my profile page I should see my profile information displayed. This ticket is intended to handle specifically the user information section, showing details about the user.

## Acceptance

- [ ] user picture in circle shape
- [ ] display name
- [ ] username / login name
- [ ] description
- [ ] number of followers with people icon
- [ ] number of people following
- [ ] star icon with star count
- [ ] building icon with company name
- [ ] map marker icon with location
- [ ] link icon with blog / website
- [ ] divider
- [ ] organizations title
- [ ] any organizations will show as a square button with the org logo, that will navigate to the organization page when clicked

## Notes

**Comment by Reshurum** [comment]
It appears this has already been completed. 

![Image](https://user-images.githubusercontent.com/4316134/174663657-1c5ca387-a189-42b3-b0e9-3db82ea15775.png)

**Comment by Reshurum** [comment]
CC: @dustinsgoodman ☝

**Comment by dustinsgoodman** [comment]
Roger!
