### ISSUE TITLE
[Angular - NgRx - SCSS] Create single repo code tab view

### ISSUE THREAD

**Issue by lindakatcodes** [thisdot/starter.dev-github-showcases#198]
# Create single repo code tab view

## Background

As a user, by default when I navigate to a single repository I land on the code tab. Here I can see the folders and files found in the root directory of the repo and the name of the root branch. I can also see the repo’s readme file below the folder tree.

## Acceptance

- [ ] Branch button with icon, name of root branch, and dropdown arrow (does not need to show other branches yet)
- [ ] show root folder directories and files (relates to issue for folder navigation)

## Notes

**Comment by lindakatcodes** [comment]
This appears to be done with the work on issue #203 . Please confirm and close if correct.

**Comment by SDaian** [comment]
That's right @lindakatcodes this was done on #203. Will proceed to close.
