### ISSUE TITLE
Translate components from Nextjs app to Remix

### ISSUE THREAD

**Issue by tvanantwerp** [thisdot/starter.dev-github-showcases#226]
Located at [`starter.dev-showcases/next-react-query-tailwind/src/components/`](https://github.com/thisdot/starter.dev-showcases/tree/main/next-react-query-tailwind/src/components).

These will need to be rewritten to work with Remix.

Remix does not currently support CSS Modules. Since all of the CSS files I've seen so far just use Tailwind's `@apply` directive to create classes, it will be easy enough to copy-paste those Tailwind classes and inline them in the components.

Since Remix includes backend functionality that Next doesn't, data fetching will need to be redone. [But that's a separate issue](https://github.com/thisdot/starter.dev-showcases/issues/63). Given the way Remix divides components and routes, I think all data fetching should be handled by the loaders in the routes and all components should be pure functional components. It should also make it easier to test them in Storybook that way, too.

**Comment by dustinsgoodman** [comment]
Closing as this ticket has been mostly broken down into other tickets and isn't relevant.
