### ISSUE TITLE
Figure out demo hosting for Remix example

### ISSUE THREAD

**Issue by tvanantwerp** [thisdot/starter.dev-github-showcases#227]
Remix does not currently have good support for AWS Amplify, which is being used to host other sample apps. We will need to either 1) figure out how to get it to play nice with Amplify or 2) host it somewhere else.

Relevant discussions:
- https://discord.com/channels/770287896669978684/777863791093612565/930536604110569503
- https://github.com/remix-run/remix/issues/806
>
>  ryanflorence commented on Dec 19, 2021
>
> Somebody who knows AWS Amplify will need to help out here. Remix is pretty simple to host. To deploy a Remix app the server needs to:
>
>  -  Serve static assets out of public/
>  -  Route all other requests to a lambda
>
> That lambda would have a Remix adapter that adapts the AWS Amplify request into a web fetch Request. I'm sure the adapter will be pretty much identical to the remix-architect and remix-netlify adapters. So you can look in there for hints.
>
> When I've looked at AWS amplify it all seemed very browser-oriented and it wasn't obvious how to set up those two requirements. We welcome any amplify experts to help out here :)

**Comment by dustinsgoodman** [comment]
Remix stacks launched with an AWS example. I wonder if we can adopt their ideas and make it work with what we're doing: https://github.com/remix-run/grunge-stack

**Comment by dustinsgoodman** [comment]
Blocked by #274
