### ISSUE TITLE
[Remix + GraphQL + Tailwind] UserDropdown component with NavBar

### ISSUE THREAD

**Issue by WillHutt** [thisdot/starter.dev-github-showcases#228]
# Background
We need a navbar for users so they can access their profile and signout.

See this reference component: https://github.com/thisdot/starter.dev-showcases/tree/main/next-react-query-tailwind/src/components/NavBar
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/1815379/166316194-25228e25-3abc-40ec-8177-b83075db672f.png">

# Acceptance
- The app should have a navbar
- The logo should go back to the dashboard
- The image of the user should be on the right which is a dropdown toggle
- The dropdown should have a logout button and a "view profile" button

**Comment by dustinsgoodman** [comment]
There is an existing PR in the legacy project https://github.com/thisdot/starter.dev-showcases/pull/93/files
