### ISSUE TITLE
[CRA-RXJS-SC] Get Profile information from GitHub API

### ISSUE THREAD

**Issue by ktrz** [thisdot/starter.dev-github-showcases#231]
# Get Profile information from GitHub API

## Background

For the profile page, we want to fairly closely resemble the GitHub user page. This section is focused on the user “card”, where you can see profile information about the user.

## Acceptance

- [ ] Get user info from GitHub API
- [ ] For display on profile page; data needed:
    - [ ] Photo
    - [ ] Name (display name)
    - [ ] username (login name)
    - [ ] description
    - [ ] followers
    - [ ] following
    - [ ] stars
    - [ ] company info
    - [ ] location info
    - [ ] blog link
    - [ ] organizations (need name and avatar)

**Comment by markshenouda** [comment]
This ticket is solved by https://github.com/thisdot/starter.dev-github-showcases/issues/231
