### ISSUE TITLE
[CRA-RXJS-SC] Need to fix inaccuracies with the updated_at field for RxJS App

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/starter.dev-github-showcases#234]
The RxJS app is not updating correctly for the updated_at field for the individual repos. It seems to be lagging behind. 
Here is the [repo](https://github.com/thisdot/starter.dev-showcases/tree/main/cra-rxjs-styled-components) for the RxJS app

In the `repository.tsx` file which is the components folder, this is the current code for the update_at field.
```
export default function RepositoryCard({ repository }: { repository: RepositoryWithBranchCount }) {
  const since = formatDistanceToNow(new Date(repository.updated_at), { addSuffix: true });
```

Here is a screenshot to show the differences.

Screenshot from  GitHub
<img width="711" alt="Screen Shot 2022-02-18 at 8 28 27 AM" src="https://user-images.githubusercontent.com/67210629/154723117-dbc2f192-6a19-4b15-8b9a-1202e7371e29.png">

Screenshot from RxJS app
<img width="782" alt="Screen Shot 2022-02-18 at 8 29 42 AM" src="https://user-images.githubusercontent.com/67210629/154723467-787e5e00-252c-4015-92c6-6178354d1903.png">

**Comment by tyrelchambers** [comment]
Based on a little bit of investigation, it looks like Github is using the "pushed_at" property to show when it was last updated, rather than our implementation which uses "updated_at".
