### ISSUE TITLE
[angular-apollo-tailwind] Fix build issues

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#260]
Builds are currently failing with the following issues:
![Image](https://user-images.githubusercontent.com/1815379/167730091-226d743b-6b02-4b82-b8f0-74d5bfa07d26.png)

@BrettZeidler says it's due to his recent change and that:
> `yarn generate` needs to run after the install step

So we probably need to update the `amplify.yml` accordingly.

**Comment by BrettZeidler** [comment]
Verified #261 resolved this deploy issue:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/54006458/167733361-7e967dce-50a8-42ea-af5e-b222b40f5c96.png">
