### ISSUE TITLE
[Remix + GraphQL + Tailwind] Remove "Edit Profile" from user/org pages

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#267]
We're not going to do user profile editing so this button needs to go away:

![Image](https://user-images.githubusercontent.com/1815379/167938136-b27b268f-34d1-4224-b66c-4e500bde9784.png)

**Comment by WillHutt** [comment]
Issue is a part of this ticket: https://github.com/thisdot/starter.dev-github-showcases/issues/243

**Comment by dustinsgoodman** [comment]
Closing as a dupe! Thanks!
