### ISSUE TITLE
[Angular - NgRx - SCSS] Adjust log in logic to persist authentication status

### ISSUE THREAD

**Issue by lindakatcodes** [thisdot/starter.dev-github-showcases#331]
Because the urls for the deploy preview and the signIn redirect (which is hard coded in the env variables) are different, the NgRx store doesn’t persist across them, and so the calls to set a user as authenticated and to store the session cookie don’t work. It’s fine locally and on the fully deployed instance since those urls will match, but will prevent the previews from letting anyone log in. 

Will need some discussion on how best to adjust for this for deploy previews:
- Get the current url dynamically, and use that instead of hard coding the url paths?
- Move the logic that saves the session cookie to a route guard or something similar, and adjust the store logic to check for the cookie first?
- Move all auth logic out of the NgRx store and make it local / cookie based?

Not sure the best path forward. But the deploy previews would be helpful enough for reviewing that finding a solution for this is worth figuring out.

Edit: Looking into all these possibilities, but adding in some acceptance criteria for the end result.

**Acceptance criteria:**
- Sign in should be possible locally, through deploy previews, and through the deployed app
- If a user is signed in, they should stay signed in after a page refresh

**Comment by dustinsgoodman** [comment]
@ktrz or @morgnism if you have time, I'd love your thoughts on this for this app.
