### ISSUE TITLE
[CRA-RxJS-SC] Refractor Repo sub-header & tab navigation

### ISSUE THREAD

**Issue by iansamz** [thisdot/starter.dev-github-showcases#337]
Refractor and fix

- [x] Refractor sub-header and route outlet for repos
- [x] issues on tab navigation showing wrong numbers
- [x] Tab navigation when active

**Comment by vyktoremario** [comment]
@iansamz I think a screenshot or a video of the issue with reference to the actual behaviour will give this more context

**Comment by iansamz** [comment]
Noted. Updating
