### ISSUE TITLE
[Vue + Apollo + Quasar] Create navigation header

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#377]
## Background

As a user, I should see a header with the GitHub logo as a home button on the left, and my user profile picture on the right attached to a dropdown menu. The menu should show links for navigating to my profile and a sign out link.

## Acceptance

- [x] Top nav
  - [x] GitHub logo on the left
  - [x] User avatar with dropdown on the right
  - [x] Navigation to profile in the dropdown (can point to not yet existing page)
  - [x] Logout link in the dropdown (can point to not yet existing functionality yet)
- [ ] Placeholder for main content

## Notes

**Comment by AllanJeremy** [comment]
Could you please clarify on the "Placeholder for main content"? 

Is it placeholder content while we get data from endpoints
or
Placeholder loading content before the endpoint data appears on the page?

**Comment by dustinsgoodman** [comment]
Completed as part of a separate issue
