### ISSUE TITLE
[vue-apollo-quasar] Create single repo code tab view

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#400]
## Background

As a user, by default when I navigate to a single repository I land on the code tab. Here I can see the folders and files found in the root directory of the repo and the name of the root branch. I can also see the repo’s readme file below the folder tree.

## Acceptance

- [x] Branch button with icon, name of root branch, and dropdown arrow (does not need to show other branches yet)
- [x] show root folder directories and files (relates to issue for folder navigation)

**Comment by dustinsgoodman** [comment]
@hdJerry @WillHutt do either of you have a start on this yet? I can't find a branch or PR. Planning on reassigning.

**Comment by hdJerry** [comment]
Sorry, my system needed to be serviced so i couldn't push what i started working on. done so now.
@dustinsgoodman
