### ISSUE TITLE
[vue-apollo-quasar] Create file view

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#406]
## Background

As a user, if I’m viewing a single repository and click on an individual file, I am navigated to a single page view of that file. This should look similar to how a file would look on GitHub itself.

## Acceptance

- [ ] clicking on a file in a repo displays that file

**Comment by Atrophius** [comment]
@hdJerry This is likely done or close to done? Need a status update on where it currently stands. If there's outstanding work, please take it over and finish.

**Comment by hdJerry** [comment]
Yes, it partially done. I think it need styling @Atrophius.
