### ISSUE TITLE
[remix-gql-tailwind] Architectural review of current kit & showcase and any cleanup recommendations

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#489]

**Comment by tvanantwerp** [comment]
## README

The `README.md` file contains only a minimum amount of information about Storybook and authenticating with GitHub. The majority of the file hasn’t been edited in 6 months. Doesn’t explain many things, e.g., Arc.

## Storybook

Storybook is not officially supported by Remix yet. Since this starter’s initial implementation of Storybook, there’s been a great deal of detailed discussion about how Remix should support it [here](https://github.com/remix-run/remix/discussions/2481).

## `.env.example`

Does not include all env variables required. Missing `GITHUB_CLIENT_ID`, `GITHUB_CLIENT_SECRET`, and `BASE_URL`.

## Running the project

Could not even get the project to run. After adding necessary `.env` variables and clicking the Login with GitHub button, I ended up on an error screen. The login button correctly goes to GitHub, then returns to the correct `/auth/github/callback` route with the necessary codes. I used the same GitHub app credentials in `.env` as when I started work on the project six months ago. On redirect to the root `/` route, the server returns a 500 error. The CatchBoundary in `root.tsx` is used, but rendered as text rather than HTML. CLI states: **Error: GraphQL Error (Code: 405)**.

Full error:

```
Error

GraphQL Error (Code: 405): {"response":{"error":"<!DOCTYPE html><html lang=\"en\"><head><title>Error</title><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/><title>GitHub Demo App</title><link rel=\"stylesheet\" href=\"/_static/build/_assets/tailwind-QCS2ZNJQ.css\"/></head><body><div class=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-center\"><div class=\" mb-8 text-9xl\">405</div><div class=\"mb-5 text-2xl\"><span class=\"\">Ooops...</span><br/></div><div class=\" rounded bg-gray-900 px-7 py-2 text-white\"><a class=\" \" href=\"/\">Go to Home</a></div></div><script>\n (() => {\n let protocol = location.protocol === \"https:\" ? \"wss:\" : \"ws:\";\n let host = location.hostname;\n let socketPath = protocol + \"//\" + host + \":\" + 8002 + \"/socket\";\n\n let ws = new WebSocket(socketPath);\n ws.onmessage = (message) => {\n let event = JSON.parse(message.data);\n if (event.type === \"LOG\") {\n console.log(event.message);\n }\n if (event.type === \"RELOAD\") {\n console.log(\"💿 Reloading window ...\");\n window.location.reload();\n }\n };\n ws.onerror = (error) => {\n console.log(\"Remix dev asset server web socket error:\");\n console.error(error);\n };\n })();\n </script></body></html>","status":405,"headers":{}},"request":{"query":"\n query CurrentUser {\n viewer {\n avatarUrl\n login\n name\n }\n }\n"}}
```

The same error is displayed twice in the terminal, likely due to the use of two queries at the `/` route. It gives little additional insight:

```
[dev:*arc] There was an error running the data loader for route root
[dev:*arc] Error: GraphQL Error (Code: 405): {"response":{"error":"<!DOCTYPE html><html lang=\"en\"><head><title>Error</title><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/><title>GitHub Demo App</title><link rel=\"stylesheet\" href=\"/_static/build/_assets/tailwind-QCS2ZNJQ.css\"/></head><body><div class=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-center\"><div class=\" mb-8 text-9xl\">405</div><div class=\"mb-5 text-2xl\"><span class=\"\">Ooops...</span><br/></div><div class=\" rounded bg-gray-900 px-7 py-2 text-white\"><a class=\" \" href=\"/\">Go to Home</a></div></div><script>\n                (() => {\n                  let protocol = location.protocol === \"https:\" ? \"wss:\" : \"ws:\";\n                  let host = location.hostname;\n                  let socketPath = protocol + \"//\" + host + \":\" + 8002 + \"/socket\";\n\n                  let ws = new WebSocket(socketPath);\n                  ws.onmessage = (message) => {\n                    let event = JSON.parse(message.data);\n                    if (event.type === \"LOG\") {\n                      console.log(event.message);\n                    }\n                    if (event.type === \"RELOAD\") {\n                      console.log(\"💿 Reloading window ...\");\n                      window.location.reload();\n                    }\n                  };\n                  ws.onerror = (error) => {\n                    console.log(\"Remix dev asset server web socket error:\");\n                    console.error(error);\n                  };\n                })();\n              </script></body></html>","status":405,"headers":{}},"request":{"query":"\n  query CurrentUser {\n    viewer {\n      avatarUrl\n      login\n      name\n    }\n  }\n"}}
[dev:*arc]     at /Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/server/node_modules/graphql-request/src/index.ts:325:11
[dev:*arc]     at step (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/server/node_modules/graphql-request/dist/index.js:63:23)
[dev:*arc]     at Object.next (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/server/node_modules/graphql-request/dist/index.js:44:53)
[dev:*arc]     at fulfilled (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/server/node_modules/graphql-request/dist/index.js:35:58)
[dev:*arc]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev:*arc]
[dev:*arc] There was an error running the data loader for route root
[dev:*arc] Error: GraphQL Error (Code: 405): {"response":{"error":"<!DOCTYPE html><html lang=\"en\"><head><title>Error</title><meta charSet=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/><title>GitHub Demo App</title><link rel=\"stylesheet\" href=\"/_static/build/_assets/tailwind-QCS2ZNJQ.css\"/></head><body><div class=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-center\"><div class=\" mb-8 text-9xl\">405</div><div class=\"mb-5 text-2xl\"><span class=\"\">Ooops...</span><br/></div><div class=\" rounded bg-gray-900 px-7 py-2 text-white\"><a class=\" \" href=\"/\">Go to Home</a></div></div><script>\n                (() => {\n                  let protocol = location.protocol === \"https:\" ? \"wss:\" : \"ws:\";\n                  let host = location.hostname;\n                  let socketPath = protocol + \"//\" + host + \":\" + 8002 + \"/socket\";\n\n                  let ws = new WebSocket(socketPath);\n                  ws.onmessage = (message) => {\n                    let event = JSON.parse(message.data);\n                    if (event.type === \"LOG\") {\n                      console.log(event.message);\n                    }\n                    if (event.type === \"RELOAD\") {\n                      console.log(\"💿 Reloading window ...\");\n                      window.location.reload();\n                    }\n                  };\n                  ws.onerror = (error) => {\n                    console.log(\"Remix dev asset server web socket error:\");\n                    console.error(error);\n                  };\n                })();\n              </script></body></html>","status":405,"headers":{}},"request":{"query":"\n  query CurrentUser {\n    viewer {\n      avatarUrl\n      login\n      name\n    }\n  }\n"}}
[dev:*arc]     at /Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/server/node_modules/graphql-request/src/index.ts:325:11
[dev:*arc]     at step (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/server/node_modules/graphql-request/dist/index.js:63:23)
[dev:*arc]     at Object.next (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/server/node_modules/graphql-request/dist/index.js:44:53)
[dev:*arc]     at fulfilled (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/server/node_modules/graphql-request/dist/index.js:35:58)
[dev:*arc]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Storybook didn’t work properly, either. The mocks to replace <Link> with <a> didn’t seem to be working as expected, and many components displayed errors as a result.

```
useHref() may be used only in the context of a <Router> component.
```

If these are known errors with a fix, I'm not aware of them. Investigations are ongoing.

**Comment by tvanantwerp** [comment]
The function [RepoNavigation](https://github.com/thisdot/starter.dev-github-showcases/blob/7c359c21433ec75308d5b4b00bbbccfa270ef5b9/remix-gql-tailwind/app/components/FileExplorerNav/FileExplorerNav.tsx#L7), which somewhat confusingly is the sole and default export from a file named `FileExplorerNav`, is missing React `key`s.

**Comment by tvanantwerp** [comment]
These "buttons" are just `spans` with `hover:cursor-pointer` styles. Clicking them does nothing.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/2487968/180521748-4a88af61-c7f8-4e4d-9211-156a650444d6.png">

**Comment by tvanantwerp** [comment]
[Absence](https://github.com/thisdot/starter.dev-github-showcases/blob/7c359c21433ec75308d5b4b00bbbccfa270ef5b9/remix-gql-tailwind/app/components/UserProfile/UserProfile.view.tsx#L91) of `http://` in profile `websiteUrl` causes links to render as relative to the app root. Adding `http://` fixes this.

## Problem

<img width="186" alt="image" src="https://user-images.githubusercontent.com/2487968/180537978-4367ad40-5ef3-4bda-b0b0-816d94600e8b.png">


## Fix

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2487968/180531775-20b38521-f373-44c6-ab10-21f5d7376d65.png">

**Comment by tvanantwerp** [comment]
Similar to the user profile website link problem, the website links for repos are also set to be local. [Replace](https://github.com/thisdot/starter.dev-github-showcases/blob/7c359c21433ec75308d5b4b00bbbccfa270ef5b9/remix-gql-tailwind/app/components/RepoAboutWidget/HomepageUrl.tsx#L17) the `<Link>` with `<a>`.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/2487968/180553501-d730cf4e-d728-40de-b7c1-e8b67e440a12.png">

**Comment by tvanantwerp** [comment]
Mobile styles could use some polish.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/2487968/180554481-6c4fa215-0d1b-4129-a268-24a5d8a423c3.png">

**Comment by tvanantwerp** [comment]
Lots of components in the `components` directory, and names aren't always the easiest to figure out.

<img width="211" alt="image" src="https://user-images.githubusercontent.com/2487968/180556476-ab030d5c-c4d7-4ba0-9639-edca77c9278d.png">

The contents of each of these components can be very different. Sometimes you might be looking for a specific component and not finding it because it's not top-level, but hidden inside another component's directory.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/2487968/180559022-7a1d3098-dd93-4407-98a8-16c37b1e23f8.png">

The existing hierarchy of components could probably be refactored for clarity.

Example:

```
components/
├─ Navbar/
│  ├─ A top-level component that is present on all pages
├─ Shared/
│  ├─ components used across other components, like styled buttons
├─ Profiles/
│  ├─ UserProfile/
│  │  ├─ various sub components go here
│  ├─ OrgProfiles/
│  │  ├─ etc...
├─ Repositories/
│  ├─ Header/
│  │  ├─ Navigation/
│  ├─ FileExplorer/
├─ ...
```

**Comment by tvanantwerp** [comment]
What minimal testing is set up in this starter itself either 1) doesn't exist, in the case of Vitest and `yarn test`, or 2) doesn't pass, in the case of local Cypress testing.

I'm trying to use the starter-wide Cypress tests, but so far no luck. Error:

```
[mock:*remix] Error: remix dev is not supported for custom servers.
[mock:*remix]     at Object.dev (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/node_modules/@remix-run/dev/cli/commands.js:262:11)
[mock:*remix]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[mock:*remix]     at dev (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/node_modules/@remix-run/dev/cli/run.js:183:3)
[mock:*remix]     at Object.run (/Users/tvanantwerp/Documents/thisdot/starter.dev-github-showcases/remix-gql-tailwind/node_modules/@remix-run/dev/cli/run.js:496:7)
[mock:*remix] npm run mock:remix exited with code 1
```

**Comment by tvanantwerp** [comment]
I don't know what `remix-gql-tailwind/server/index.js.map` is or does—something to do with the arc deploy?—but it looks like the kind of auto-generated file that doesn't need to be in VCS.

**Comment by dustinsgoodman** [comment]
I am laying my stamp of approval via this comment saying DONE
