### ISSUE TITLE
[remix-gql-tailwind] Fix RepoNavigation naming and React Best Practices

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#505]
# Background
The function [RepoNavigation](https://github.com/thisdot/starter.dev-github-showcases/blob/7c359c21433ec75308d5b4b00bbbccfa270ef5b9/remix-gql-tailwind/app/components/FileExplorerNav/FileExplorerNav.tsx#L7), which somewhat confusingly is the sole and default export from a file named `FileExplorerNav`, is missing React `key`s.

See https://github.com/thisdot/starter.dev-github-showcases/issues/489#issuecomment-1192902473 for original comment

# Acceptance
- Rename FileExplorerNav file that contains RepoNavigation to RepoNavigation
- Update render to include keys in loops

**Comment by sheerikie** [comment]
# What was done?
- Replaced FileExplorerNav to reponavigation
- Added keys to loop item


# Screenshot/Video/GIF of Changes (if applicable)
TODO: @sheerikie 
N/A

# Related Ticket(s)
Resolves #505
