### ISSUE TITLE
[qwik] Review Qwik kit

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#520]
# Acceptance
- Review https://github.com/thisdot/starter.dev/pull/262
- Write up tickets for any missing features based on our standards for kits
- Determine full tech stack used

**Comment by honzikec** [comment]
Looks like a lot of features are missing (example components, styling library, tests, data fetching...) - I've created tickets on the starter.dev board.

The tech stack so far seems to be just:
- vite
- @builder.io/qwik
- @builder.io/qwik-city

(+ express & node-fetch)

The rest of the stack needs to be decided on and added.

@dustinsgoodman, what would be the next steps?

**Comment by honzikec** [comment]
@dustinsgoodman, I've mentioned the PR in the issues, so they should be visible on the PR, so I'll just drop a comment asking for the feedback 👍

**Comment by dustinsgoodman** [comment]
I think you're good to close this one out!
