### ISSUE TITLE
[cra-rxjs-sc] Audit app for any architectural improvements and features that are incomplete

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#522]
# Acceptance
As either a write up in Google Docs or as comments on this issue, please provide us with:
- Any bugs you find clicking through the app
- Any architectural issues you see with components, their styles, or general cleanup required

# Notes
See #489 for a good example

**Comment by tvanantwerp** [comment]
During signing in non-Chrome browsers, there is a redirect loop where the user gets stuck at the `/signin` route despite successfully logging in.

**Comment by tvanantwerp** [comment]
Pull request API queries not currently set up to fetch more than 30 total results. Does not show correct number of PRs open or closed.

**Comment by markshenouda** [comment]
Also, there is a key missing, probably on a `.map` loop

![Image](https://user-images.githubusercontent.com/49324987/185689670-3eacd5c0-066c-47fc-ba6e-d998ff67ea9a.png)

**Comment by tvanantwerp** [comment]
`components` directory has a mixed of PascalCase and kebab-case directory names. It would be nice to standardize it.

<img width="221" alt="image" src="https://user-images.githubusercontent.com/2487968/185718922-185a77da-cea5-4fba-8b9c-31f357cc448f.png">

**Comment by tvanantwerp** [comment]
`.editorconfig` uses spaces for indentation. Tabs would be better [for a11y reasons](https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f).

Also, some of these rules might be better off inside the `.prettierrc` instead.

And speaking of Prettier, maybe set up husky and lint-staged to make formatting automatic on commit, so we don't have to worry about individual editor setups matching desired formatting.

**Comment by tvanantwerp** [comment]
I know why the `.env` only needs two env vars, but it might be worth explaining in the README somewhere that it's using a backend shared by all the starters to get authentication tokens.

**Comment by tvanantwerp** [comment]
Storybook is installed, but no components have stories.

**Comment by dustinsgoodman** [comment]
Everything with a 👍 from me is converted to a ticket

**Comment by BigAB** [comment]
> `cleanup`

`App.tsx` has an unused import of `UserProvider`, it's causing  a lint warning

**Comment by BigAB** [comment]
> `cleanup`

`component/dropdown` sounds like a general use component but is a very specific user menu dropdown, suggest renaming component

**Comment by BigAB** [comment]
> `cleanup`

Having to have the `<Header />` component in `App.tsx`, `profile.tsx` and `/routes/repo/index.tsx` feels like we are misusing react-router.

There should be a way to use the `Outlet` and `Route`s better so that the `<Header />` only needs to be included 1 time

**Comment by BigAB** [comment]
> `cleanup`

Having some `index.ts` files be "barrell" files (with just an export \* from ...) and some having source code seems inconsistent, we should pick one or the other

(and the one we should pick is having only exports in the index.ts files or removing them altogether), otherwise you can get stack traces in errors that are like just a wall of `index.ts`)

**Comment by BigAB** [comment]
> `broken`

After login the gists and repos remain empty until after hitting refresh again

https://user-images.githubusercontent.com/76821/187538344-08455ee7-a6f7-42c6-95cd-77b340ca4b27.mp4

**Comment by BigAB** [comment]
> `broken`

The link in the [**Cloning the repository**](https://github.com/thisdot/starter.dev-github-showcases/tree/main/cra-rxjs-styled-components#cloning-the-repository) section of the README.md leads to a 404 page

**Comment by BigAB** [comment]
> `broken`

There are network errors in the console when you see the login page, this is probably unnecessary, and we can make requests conditionally

**Comment by BigAB** [comment]
> `broken`

The profile page shows a broken image and has alt text "Avatar" until the image loads

<img width="401" alt="Screen Shot 2022-08-30 at 2 41 06 PM" src="https://user-images.githubusercontent.com/76821/187539204-69672b92-fae8-45fd-ace4-e8efb06de557.png">

**Comment by BigAB** [comment]
> `broken`

View all repositories `ViewRepositoriesLink` goes to the user's profile page, not to view all repositories

<img width="608" alt="image" src="https://user-images.githubusercontent.com/76821/187539473-7a50b548-47f0-416a-9f83-6043ef7d7568.png">

**Comment by BigAB** [comment]
> `opinion based`

In general there is a lot of layout shifting while loading, I think we should try to use suspense and perhaps skeletons or something to prevent layout shifting

**Comment by BigAB** [comment]
> `opinion based` 

I think it is unusual to have the routes in `/src/index.tsx`, I think every example I have ever seen has them in `App.tsx`

I'd recommend something more like:

```ts
// index.ts
import React from 'react';
import ReactDOM from 'react-dom';
import reportWebVitals from './reportWebVitals';
import App from './app';
import './index.css';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```
```ts
// app.ts
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import AuthGuard from './components/AuthGuard';
import Home from './routes/Home';
import Redirect from './routes/redirect';
import SignIn from './routes/sign-in';
import TopRepos from './routes/user-top-repos';
import RepoPullRequest from './routes/repo/repository-pull-request';
import RepoIssues from './routes/repo/repository-issues';
import Repo from './routes/repo';
import UserRepos from './components/user-repos';
import UserProfile from './routes/profile';
import RepoBranchRoot from './routes/repo/repository-code';
import RepoBranchTreePath from './routes/repo/repository-code/repository-tree/repository-tree';
import RepoBranchBlobPath from './routes/repo/repository-code/repository-blob/repository-blob';
import { UserProvider } from './context/UserProvider';

function App() {
  return (
    <UserProvider>
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Home />}>
            <Route
              path=""
              element={
                <AuthGuard>
                  <TopRepos />
                </AuthGuard>
              }
            />
          </Route>
          <Route
            path="/orgs/:username"
            element={
              <AuthGuard>
                <UserRepos isOrg />
              </AuthGuard>
            }
          />
          <Route
            path="/:username/:repo"
            element={
              <AuthGuard>
                <Repo />
              </AuthGuard>
            }
          >
            <Route path="" element={<RepoBranchRoot />} />
            <Route path="tree/:branch/*" element={<RepoBranchTreePath />} />
            <Route path="blob/:branch/*" element={<RepoBranchBlobPath />} />
            <Route path="issues" element={<RepoIssues />} />
            <Route path="pull-requests" element={<RepoPullRequest />} />
          </Route>
          <Route
            path="/:username"
            element={
              <AuthGuard>
                <UserProfile />
              </AuthGuard>
            }
          ></Route>
          <Route path="signin" element={<SignIn />} />
          <Route path="redirect" element={<Redirect />} />
        </Routes>
      </BrowserRouter>
    </UserProvider>
  );
}

export default App;
```

...which I think is a much more common pattern

**Comment by BigAB** [comment]
> `opinion based`

I believe we should create the observables outside of the components/hooks. Though it can be tempting to create the observables in components like in `RepoPage.data.tsx` or `UserProvider.tsx`, or in hooks like `useSetToken()` and `useRepositoryIssues()`, I have found it far better separate the "react" code from the RxJS code and combine them where necessary with a `useObservable()` or similar hook.

I find this makes testing easier, and reduces the complexity, as anything with asynchronous state can done in RxJS and leave the visual UI and component state to react.

**Comment by BigAB** [comment]
> `opinion based`

I think we should list react-router v6 as part of the **Featured Tech Stack** in the `README.md` as it is such a vital part of how the project is organized
