### ISSUE TITLE
[vue3-apollo-quasar] Fix profile story data not loading

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#534]
Profile related stories do not load profile data in stories
  - This is because they try making a request to the github graphql API which ends up being unauthorized. That means the story that should contain profile information (username, profile pic) ends up blank.

# Acceptance
- The profile story data should be mocked and not come from a live call

# Notes
See #533 - we're adding some utilities there to help

**Comment by hdJerry** [comment]
This is blocked by #533 .
