### ISSUE TITLE
[ALL KITS] Fix redirect loop on login

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#540]
From @tvanantwerp:
> During signing in non-Chrome browsers, there is a redirect loop where the user gets stuck at the /signin route despite successfully logging in.

Confirmed issue on Firefox & Safari.

# Acceptance
- Fix redirect login loop

**Comment by kodejuice** [comment]
PR #586  

May need access to `api.starter.dev` code to debug, as the endpoint doesn't return the `access_token` on non chromium browsers (like Firefox).

**Comment by dustinsgoodman** [comment]
The code is in this repo in the backend project.
