### ISSUE TITLE
[CRA - RxJS - SC] Fix gists and repos data at login

### ISSUE THREAD

**Issue by Atrophius** [thisdot/starter.dev-github-showcases#597]
After login the gists and repos remain empty until after hitting refresh again

https://user-images.githubusercontent.com/39612839/189458594-e7329725-8920-4aa6-a16a-c0def6dd91e2.mp4

# Acceptance

At login the gists and repos data should load correctly

**Comment by WillHutt** [comment]
Closed as my PR attached to it no longer has any new changes with the main. So it appears solved.
