### ISSUE TITLE
[nuxt-pinia-tailwind] Create navigation header

### ISSUE THREAD

**Issue by Atrophius** [thisdot/starter.dev-github-showcases#629]
## Background

As a user, I should see a header with the GitHub logo as a home button on the left, and my user profile picture on the right attached to a dropdown menu. The menu should show links for navigating to my profile and a sign out link.

## Acceptance

- [ ] Top nav
  - [ ] GitHub logo on the left
  - [ ] User avatar with dropdown on the right
  - [ ] Navigation to profile in the dropdown (can point to not yet existing page)
  - [ ] Logout link in the dropdown (can point to not yet existing functionality yet)
- [ ] Placeholder for main content

## Notes

**Comment by hdJerry** [comment]
There is a header but these are missing

- User avatar with dropdown on the right
-  Navigation to profile in the dropdown (can point to not yet existing page)
-  Logout link in the dropdown (can point to not yet existing functionality yet)
