### ISSUE TITLE
[solidjs-pod] 05 Get Gists from GitHub API

### ISSUE THREAD

**Issue by Zelig880** [thisdot/starter.dev-github-showcases#689]
# Get Gists from GitHub API

## Background

We want to show the user a list of their gists.

## Acceptance

- [x] Get gists from GitHub API
- [x] For display on main page; data needed:
    - [x] Name of gist
    - [x] html_url

**Comment by hdJerry** [comment]
This API can be fully implemented when #695 is merged as it was done before this.
