### ISSUE TITLE
[solidjs-pod] tech-debt in auth flow

### ISSUE THREAD

**Issue by mbicknese** [thisdot/starter.dev-github-showcases#744]
The current setup as implemented in #734 works, but could use some love.

1. The usage for `createResource` is a little verbose, it would be nice if we didn't need to wrap in additional try-catch statements, as well as being able to drop the return empty promise.
2. The user makes a round-trip to the signin page, should we show that it's currently authenticating there? (very fast users might click the button)
3. Setting the auth token is tightly coupled with the signing page. These should be separated.

**Comment by AllStackDev1** [comment]
I believe this ticket has already been taken care of, with the refactoring we have done the last time.
