### ISSUE TITLE
[qwik-pod] 35 Add project to docs site

### ISSUE THREAD

**Issue by Zelig880** [thisdot/starter.dev-github-showcases#787]
# Add project to docs site

## Background

Since these are meant to be showcases that anyone can view and use as templates, we want to take some time to add them to the documentation site. We want to include notes on any architecture decisions specific to the tech stack that were made, as well as steps for how to run, build, and test the showcase. A link to the currently deployed site is beneficial as well.

## Acceptance

- [ ] Add project to main documentation site
    - [x] Link to project folder
    - [x] Write out tech stack
    - [x] Short description
    - [x] Link to deployed version

## Notes
<br>
<br>
<br>
<br>

**Other eventual adds**
(doesn’t need an issue ticket, but just for future notes if we want to go further)

- [ ] make star / watch / fork buttons work
- [ ] make branch dropdown work
- [ ] allow pagination for issues / pull request tabs in single repo view

**Comment by AllStackDev1** [comment]
Resolved by in #https://github.com/thisdot/starter.dev/pull/542
