### ISSUE TITLE
[qwik-pod] Fix Back Arrow Issue On Browser Bar When Going Through Profile Page Repo

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#910]
![Image](https://user-images.githubusercontent.com/1828602/202785967-5f483a86-e422-4f6b-8abb-8798de40833e.jpg)

**Comment by AllStackDev1** [comment]
Issue resolved in PR https://github.com/thisdot/starter.dev-github-showcases/pull/924
