### ISSUE TITLE
[qwik-pod] Fix Files Not Showing When Visiting Repo Through Profile Page

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#911]
Below, we can see some files are not showing as expected

![Image](https://user-images.githubusercontent.com/28502531/203549668-cb80de2d-8b7c-4daa-8616-eff4b842dbf9.jpg)

**Comment by hdJerry** [comment]
I think this was misinterpreted @kenslachtajr @SDaian 
When going to a repo from the profile page, files don't show

**Comment by hdJerry** [comment]
Everything seems fine, this ticket can be closed as files and folders shows as expected after comparing with my original git repo.
Unfortunately we just wasted some valuable time. 

image below was from Github itself which is the same as the above.



![Image](https://user-images.githubusercontent.com/28502531/203570961-c8f02b26-2808-41d4-aaf2-30fe50ecd0e0.jpg)
