### ISSUE TITLE
Migrate Deployment to Open Source Team 

### ISSUE THREAD

**Issue by Zelig880** [thisdot/starter.dev-github-showcases#961]
Move over the deployment to Netlify as mentioned on this other ticket: https://github.com/thisdot/framework.dev/issues/480

Add a netlify badge to each site (as mentioned below):
- [x] Angular Apollo tailwind
- [x] Angular Ngrx SCSS
- [x] Next React Query Tailwind *
- [x] Cra-rxjs-styled-component *
- [x] Vue3-ts-quasar *

Migrate the site over Netlify
- [x] Angular Apollo tailwind
- [x] Angular Ngrx SCSS
- [x] Next React Query Tailwind *
- [x] Cra-rxjs-styled-component *
- [x] Vue3-ts-quasar *

Move DNS over:
- [x] Angular Apollo tailwind
- [x] Angular Ngrx SCSS
- [x] Next React Query Tailwind *
- [x] Cra-rxjs-styled-component *
- [x] Vue3-ts-quasar *

*The deployment marked with an asterix do not currently work, so please timebox this migration to 1 hour each, and if it does not work reach out to the PC so that you can have individual ticket created for this.

Notes
For the badge, I want to switch to this badge:
image

which can be fetched from https://www.netlify.com/press/#badges. The rest of Dane's implementation is fine as is.

**Comment by dustinsgoodman** [comment]
@Zelig880 some of the sites with the asterisks work. Why aren't they working?

**Comment by dustinsgoodman** [comment]
Interesting. I know the http://next-react-query-tailwind.starter.dev/ one does work so it was surprising to see that noted.

**Comment by william-mimura-thisdot** [comment]
Reopening this issue since merging the PRs above do not solve the entire issue

**Comment by lindakatcodes** [comment]
All site URLS are currently set up and deployed from Netlify, and they show Netlify DNS on them so that looks good as well.
