### ISSUE TITLE
[sveltekit-pod] Showcase Clean Up

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#966]
We need a general proofing and cleanup of the work that has been done to make sure there are no errors or omissions. 

## Acceptance Criteria

- [ ] Review the current showcase is free of errors, and everything expected has been included and is operating as expected.

Timebox: max 2 hours each

## Who has completed this:
- [x] Sochima
- [x] Ihar
- [x] Ian
- [x] Maarten
- [x] Balazs

**Comment by iansamz** [comment]
Observations: 

Remove container on repo header
![Image](https://user-images.githubusercontent.com/15368874/204488054-eab7f04e-05e2-4b44-bb51-e5bec4bd6dd1.png)

**Comment by iansamz** [comment]
This is incorrect 

![Image](https://user-images.githubusercontent.com/15368874/205266552-6975cd5e-9d06-48b9-a001-10b29e8c95f6.png)

**Comment by TapaiBalazs** [comment]
My findings so far:

1. Readme does not mention the need of copying the `.env.example` file into `.env` before starting up the dev server
2. `test:e2e` command fails initially, I needed to run `npx playwright install` to be able to run it. Should this be in the postinstall script?

I could not log in to the application, so I was only able to see the black background with the sign-in button. I investigated if it was a client side error, but it looks like it is an API error, so I stopped for today.

**Comment by mbicknese** [comment]
1. README (general) is missing a "getting started" section
2. README (showcase) is for the kit, not for how to use the showcase
3. Same as Balázs with regards to logging-in. But when I opened the console to investigate, it actually continued
4. After authorizing at point 3, I get stuck on the "redirecting..." page. (this seems to be fixed by allowing cookies in FF and might only be a dev issue)

**Comment by mbicknese** [comment]
![image](https://user-images.githubusercontent.com/5147934/210993182-43cf9fd4-d978-4fc7-b950-e1310e7aac11.png)

This version refers to the nouns, whereas GitHub and the Next starter use the verbs ("star", "watch", "fork")

**Comment by mbicknese** [comment]
![image](https://user-images.githubusercontent.com/5147934/210994314-c9b8c803-768f-41c8-b0a4-5dc8c98ffa38.png)

Feels like these should be the same width

**Comment by mbicknese** [comment]
I get the following error when trying to switch branches

![image](https://user-images.githubusercontent.com/5147934/210995483-5dbd7405-45aa-48e8-9d48-35b0bcc313d4.png)

**Comment by mbicknese** [comment]
![image](https://user-images.githubusercontent.com/5147934/210997043-93009e70-1e31-4d75-9388-f254f3185f03.png)

Mismatch of the number of issues. This might have the same cause as Ian's comment.

**Comment by mbicknese** [comment]
Trying to navigate to the next page of issues doesn't seem to work. There's no warning or error.

**Comment by mbicknese** [comment]
All testing done in **FF 108.0.1 (64-bit)** on a **Apple M1 Max** with **MacOS 13.1 (22C65)**

**Comment by mbicknese** [comment]
```
Module "source-map-js" has been externalized for browser compatibility. Cannot access "source-map-js.SourceMapConsumer" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "source-map-js" has been externalized for browser compatibility. Cannot access "source-map-js.SourceMapGenerator" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "path" has been externalized for browser compatibility. Cannot access "path.dirname" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "path" has been externalized for browser compatibility. Cannot access "path.resolve" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "path" has been externalized for browser compatibility. Cannot access "path.relative" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "path" has been externalized for browser compatibility. Cannot access "path.sep" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "url" has been externalized for browser compatibility. Cannot access "url.pathToFileURL" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "source-map-js" has been externalized for browser compatibility. Cannot access "source-map-js.SourceMapConsumer" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "source-map-js" has been externalized for browser compatibility. Cannot access "source-map-js.SourceMapGenerator" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "url" has been externalized for browser compatibility. Cannot access "url.fileURLToPath" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "url" has been externalized for browser compatibility. Cannot access "url.pathToFileURL" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "path" has been externalized for browser compatibility. Cannot access "path.resolve" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "path" has been externalized for browser compatibility. Cannot access "path.isAbsolute" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "source-map-js" has been externalized for browser compatibility. Cannot access "source-map-js.SourceMapConsumer" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "source-map-js" has been externalized for browser compatibility. Cannot access "source-map-js.SourceMapGenerator" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "fs" has been externalized for browser compatibility. Cannot access "fs.existsSync" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "fs" has been externalized for browser compatibility. Cannot access "fs.readFileSync" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "path" has been externalized for browser compatibility. Cannot access "path.dirname" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
Module "path" has been externalized for browser compatibility. Cannot access "path.join" in client code. [client.js:1847:15](http://127.0.0.1:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=89c4bd7a)
```

These warnings don't hurt anyone, but they're a bit weird. Mostly because they seem to imply that server-side code is attempted to be ran in the client, which is a bad sign.

**Comment by kodejuice** [comment]
- Clicking on links has no progress indicator, you don't know if it's loading or not

- The README markdown doesn't parse HTML
![image](https://user-images.githubusercontent.com/9017620/211016939-56344a26-eaad-49ad-a7f3-d6780dbafcac.png)

- For http://127.0.0.1:5173/thisdot/roblox-requests, the large image in the README overflows: 
![image](https://user-images.githubusercontent.com/9017620/211017998-25f7caae-75ad-4d84-8930-bc0085634367.png)

- PR/Issues page should show a message if there are none:
![image](https://user-images.githubusercontent.com/9017620/211018203-63cb0354-b4f3-400e-a9e8-5df674dfa34a.png)
v
![image](https://user-images.githubusercontent.com/9017620/211018246-b36de0d2-34ea-4ef2-a439-47dbb34f66e0.png)

- README doesn't display images

**Comment by kodejuice** [comment]
> Observations:
> 
> Remove container on repo header ![Image](https://user-images.githubusercontent.com/15368874/204488054-eab7f04e-05e2-4b44-bb51-e5bec4bd6dd1.png)

I think this depends on the width of your device

**Comment by iansamz** [comment]
Now that storybook is fixed. The storybook stories need an update based on storybook version 7.

**Comment by dustinsgoodman** [comment]
@kenslachtajr please convert to actionable tickets.
