### ISSUE TITLE
[sveltekit-pod] ButtonText.svelte pick either a prop or a slot

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#970]
File: svelte-kit-scss/src/lib/components/shared/buttons/ButtonText.svelte
Though it may seem like a good idea to have "flexibility" in our components, allowing different ways to do the same thing, all it ends
up doing is adding a little cognitive load for the decision maker and inconsistency in the code base.
Pick one, either slotted content or a `text` prop, and go with it

**Comment by BigAB** [comment]
Fixed in 52dbe92fc6d9ffaf2c0c9a1065f319da5b40217d
