### ISSUE TITLE
[sveltekit-pod] Issue Page loader: remove sequential awaits

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#971]
File: svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/[issueSearchType=issue_search_type]/+page.server.ts
- remove sequential `await`s
Discussion:
- https://github.com/thisdot/starter.dev-github-showcases/pull/953#discussion_r1031816794
Related SvelteKit feature:
- https://kit.svelte.dev/docs/load#promise-unwrapping

**Comment by BigAB** [comment]
Fixed in f65ade1c37c4b6836601ee2412364191c212a629
