### ISSUE TITLE
[solidjs-pod] Add and setup Mock Service Worker

### ISSUE THREAD

**Issue by danecando** [thisdot/starter.dev-github-showcases#993]
Needs to be hooked up to vitest or jest so we can test components that fetch data from the graphql api

We probably want to hook MSW up to Storybook similar to next-react-query-tailwind. This way we can use the mocked responses to power the component stories. 

We can use mock responses for queries from next-react-query-tailwind showcase

**Comment by hdJerry** [comment]
Yeah, provided there is a component that fetches data.
